[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
ark-groth16.workspace = true
ark-snark.workspace = true
ark-std.workspace = true
ark-relations.workspace = true
prover = { path = "../prover" }
rustls.workspace = true
tokio-rustls.workspace = true
webpki = { package = "rustls-webpki", version = "0.102.8", features = ["alloc"], default-features = false }
rustls-native-certs = "0.8"
ring = "0.17.9"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
dotenvy = "0.15"
rig-core = "0.38"
reqwest = "0.13"
bytes = "1.11.1"
